### PR TITLE
initial suggestion for module structure

### PR DESCRIPTION
**Pull request by natemellendorf**
Let's review and offer up suggestions.
I was working off of this, and would suggest we leverage version tags on the module repo.
https://blog.gruntwork.io/how-to-create-reusable-infrastructure-with-terraform-modules-25526d65f73d

### CODE REVIEW

**Comment by Japeth** [comment]
> Let's review and offer up suggestions.
> I was working off of this, and would suggest we leverage version tags on the module repo.
> https://blog.gruntwork.io/how-to-create-reusable-infrastructure-with-terraform-modules-25526d65f73d

Can we add a "providers" folder under terraform next to "modules"?

**Comment by murraybutler** [comment]
To @Japeth, I'm curious what you'd want to see in the providers folder, versus the tree structure that @natemellendorf has?  I'm totally open to the idea, just curious what your thinking was for it.

**Comment by Japeth** [comment]
@murraybutler 
ah I see what you mean.  Nevermind!

**Comment by natemellendorf** [comment]
Thanks for the input everyone!
I'll merge this to master then.

**Pull request merged**
